### ISSUE TITLE
Sprite/Tree event shapes not rendering with terrain tag defaults

### ISSUE THREAD

**Issue by Krigeris** [Dread-chan/MV3D#2]
I tried setting terrain tags 3 and 4;
3: shape(tree),pass(x)
4: shape(tree),pos(+0,+1),height(1)

with the intent that 3 works for 1 tile objects into trees/sprites (neither work) and 3 with 4 above it works for 2 tile tall objects. But this just doesn't render at all unfortunately. 

Edit: Forgot to mention its partially working in that the pass setting does work

**Comment by YoraeRasante** [comment]
> I tried setting terrain tags 3 and 4;
> 3: shape(tree),pass(x)
> 4: shape(tree),pos(+0,+1),height(1)
> 
> with the intent that 3 works for 1 tile objects into trees/sprites (neither work) and 3 with 4 above it works for 2 tile tall objects. But this just doesn't render at all unfortunately.
> 
> Edit: Forgot to mention its partially working in that the pass setting does work

that is because tree is an event shape, not a tile shape. terrain tags are only for tiles. tile shapes are only flat, fence, cross and xcross.

**Comment by Krigeris** [comment]
Alright thank you, but why? If I want a forest of 2 tile tall trees, or a
bunch of  'standing up by default' tiles that aren't a cross I currently
have to copy paste like 100 events to get that to work, I guess there's
some kind of limitation on extending that functionality to tiles?

By the way I really appreciate this plugin, having an extra dimension to
work with inspired me to reboot my project.

**Comment by YoraeRasante** [comment]
Not sure why she didn't add them to tiles either. Personally, I think it would be nice to use event shapes in tiles too. If there _is_ a limitation as you said that is unfortunate...
But to make two tile tall trees, you just need to put the top part of the tree in the same tile of the lower part, thanks to mv allowing you to put two B-E tiles in the same place in the grid (no problem if you didn't notice, I only found out when someone mentioned it on the official forums one day).
And to make tall events you just need to make them big. Character sheets for events have no real size limitation as long as they follow the pattern, you just need to put an ! at the start of the name for things to align with the grid, without them they are put about four pixels above to "pop out", an $ if you want the character sheet to be only one character, or both for... well, both.

**Comment by Electravirus** [comment]
I'm super late here, but I'll explain why sprite and tree shapes don't work on tiles.
Sprite and tree shapes rotate dynamically to face the camera.
Tiles don't have their own individual meshes, instead they're grouped together into a large mesh for the map cell. This is for performance reasons.

If I did add sprite and tree shapes for events, I'd have to create a new type of object which has its own mesh but isn't an event. That's not a bad idea actually.
